### ISSUE TITLE
Not getting beacon information in "didRangeBeacons"

### ISSUE THREAD

**Issue by Rajesh-162** [kontaktio/kontakt-ios-sdk#1]
I have added SDK & code as per kontakt.io doc and also getting call in the method "didRangeBeacons" but getting the empty array of beacons.

This is how I did the setup:

// Initiate Beacon Manager
   ` self.beaconManager = [[KTKBeaconManager alloc] initWithDelegate:self];`
    
// Request Location Authorization
   ` [self.beaconManager requestLocationAlwaysAuthorization];`

// Kontakt.io proximity UUID
    `NSUUID *proximityUUID = [[NSUUID alloc] initWithUUIDString:@"f7826da6-4fa2-4e98-8024-bc5b71e0893e"];`
    
    // Create region instance
    `self.region = [[KTKBeaconRegion alloc] initWithProximityUUID: proximityUUID identifier:@"identifier"];`
    
    // Start Monitoring
    `[self.beaconManager startMonitoringForRegion:self.region];`
    
    // You can also start ranging ...
   ` [self.beaconManager startRangingBeaconsInRegion:self.region];`

Now call comes to "didRangeBeacons" method but beacon array is just empty.

Am I missed out anything here? Please let me know.

**Comment by stoprocent** [comment]
Ok ... 
1. Do you have any beacons around ?
2. Does your beacons advertise uuid `f7826da6-4fa2-4e98-8024-bc5b71e0893e` ?

**Comment by Rajesh-162** [comment]
Yes, I have beacon around & it has uuid `f7826da6-4fa2-4e98-8024-bc5b71e0893e`, callback comes in `didRangeBeacons ` delegate method but array is empty.

I downloaded latest SDK from kontakt.io admin panel yesterday & also using the correct API Key.

**Comment by jelerson** [comment]
Did you add the nsalwaysuse to the info.plist?

**Comment by Rajesh-162** [comment]
I have NSLocationAlwaysUsageDescription key in info.plist.

**Comment by stoprocent** [comment]
@Rajesh-162 I really want to help you. We did few tests and its working fine on our end. 
Can you send me a screenshot from our administration app with your beacons on the list?

**Comment by stoprocent** [comment]
@Rajesh-162 I know it's a stupid question but are you trying to run your code on the phone or the simulator?

**Comment by Rajesh-162** [comment]
@stoprocent: I am working on device. iPhone5 having OS 9.2.
I will attach screen shot of kontakt.io admin app here.

**Comment by Rajesh-162** [comment]
![img_4477](https://cloud.githubusercontent.com/assets/5610378/12780091/dfff4506-ca91-11e5-96cc-3bf60a9d54f4.jpg)
![img_4476](https://cloud.githubusercontent.com/assets/5610378/12780093/e07a2456-ca91-11e5-9fd0-ea24c3ddd2cf.jpg)
![img_4475](https://cloud.githubusercontent.com/assets/5610378/12780094/e07c05d2-ca91-11e5-97e6-0965a0b13df1.jpg)
![img_4474](https://cloud.githubusercontent.com/assets/5610378/12780092/e06d2d28-ca91-11e5-9470-58c434e7b3f7.jpg)
![img_4472](https://cloud.githubusercontent.com/assets/5610378/12780095/e0849c6a-ca91-11e5-9859-7c67b5796a78.jpg)

Please have a look of these screen shots.
Looking forward to solution.
Thank you.

**Comment by stoprocent** [comment]
Hi
Ok now it's all clear :) All your devices are advertising as Eddystones :) so you have to use KTKEddystoneManager or switch advertising back to iBeacon.

**Comment by Rajesh-162** [comment]
@stoprocent: Thank you for solution, Its really small and I didn't catch it you should include this in your quick start guide.

And one question if I set the device as iBeacon then will it work for Android?

**Comment by stoprocent** [comment]
Yes our Android SDK fully supports iBeacon. 
You Can also leave it as eddystone but use this example ... http://developer.kontakt.io/ios-sdk/quickstart/#eddystone-support

**Comment by Rajesh-162** [comment]
ok, Many thanks for solution stoprocent .

**Comment by stoprocent** [comment]
Good to hear issue is resolved for now.
If you have any more problems just reopen this issue :)
Have a great day

**Comment by Sea-Eagle** [comment]
Hey, I'm getting same error all my beacons are broadcasting iBeacon Protocol. I'm ranging beacon pro's. but always I'm getting empty array. Device : iPhone 5s, iOS 10.3.3

**Comment by lassana** [comment]
Same problem on iPhone 5S with iOS 10.3.2. iPad 3 with iOS 9.3 works.

**Comment by where-rie** [comment]
Same as me. It occurs on iPhone5s with iOS 10.3.3, iPad Air with iOS 10.3.3, also with iOS11. 
It works on iPhone6, iPhone6Plus, iPad Pro though.
I want to know the solution.
