### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by wasimshigri** [kontaktio/kontakt-ios-sdk#10]
I am using the latest SDK which seems to be updated just 7 hours ago. Myproject name is "kontactTest" and i am having following issue (break point)  before showing the initial Screen. 

dyld: Library not loaded: @rpath/KontaktSDK.framework/KontaktSDK
  Referenced from: /var/mobile/Containers/Bundle/Application/87DCAF8B-3111-4CD7-A054-60145DE1188B/kontactTest.app/kontactTest
  Reason: image not found

**Comment by stoprocent** [comment]
Hi @wasimshigri 

This is a standard error when not embedding framework into your application.
Please make sure when SDK is installed manually you have the following setup:

![Project](https://s3.amazonaws.com/f.cl.ly/items/1K3g1L2f1F1N2k152T23/Image%202016-02-16%20at%209.51.18%20AM.png?v=e386732e)

**Comment by stoprocent** [comment]
You can follow these steps when installing SDK manually: https://github.com/kontaktio/kontakt-ios-sdk#manually
