### ISSUE TITLE
iOS 9 Inquiry

### ISSUE THREAD

**Issue by lrietze** [kontaktio/kontakt-ios-sdk#11]
Hey there,

I am working on an iOS implementation of our Android app, which will be targeting iOS 9+. My question for you is will the latest Kontakt iOS SDK work for iOS 9+? It mentions support for iOS 8 at the moment. 

Thanks!
Lucas

**Comment by stoprocent** [comment]
Hi @lrietze 

As in docs: `To use the Kontakt.io iOS SDK in your project, the minimum deployment target must be iOS 8.0.`

So to answer your question our SDK will work with any iOS version since 8.0
