### ISSUE TITLE
iOS Delegate Callbacks

### ISSUE THREAD

**Issue by jcyu0208** [kontaktio/kontakt-ios-sdk#12]
Hi,

I'd like to ask whether or not the iOS SDK supports callbacks for when an Eddystone device is "lost".
In the Android SDK we get discovered, updated, and lost callbacks. Is this supported in iOS?

Lastly, for the updated callback, since this returns only a single Eddystone device, won't this method be called too many times especially if we poll a beacon every second?

**Comment by stoprocent** [comment]
Hi

Im not sure which methods are you using but on `KTKEddsytoneManagerDelegate` there is a method called [eddystoneManager:didDiscoverEddystones:inRegion:](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Protocols/KTKEddystoneManagerDelegate.html#//api/name/eddystoneManager:didDiscoverEddystones:inRegion:). It returns set of eddystones currently in range. When Eddystone is lost it will not appear in given `NSSet`.

**Comment by jcyu0208** [comment]
Okay to clarify:
The method eddystoneManager:didDiscoverEddystones:inRegion: provides us with a reference to an NSSet that is modified continually by the API. 

So the other method, eddystoneManager:didUpdateEddystone:withFrame:, will only be called if any of the frames (EddystoneUUID, EddystoneTLM, and EddystoneURL) is modified?

If so, may I ask how do we listen to any changes in the NSSet provided in the didDiscoverDevices? My particular use case is I'm displaying data that is associated with an KTKEddystone object. If the KTKEddystone object is no longer in range, then I would also need to remove the data from the view.

**Comment by stoprocent** [comment]
> So the other method, eddystoneManager:didUpdateEddystone:withFrame:, will only be called if any of the frames (EddystoneUUID, EddystoneTLM, and EddystoneURL) is modified?

Correct.

> If so, may I ask how do we listen to any changes in the NSSet provided in the didDiscoverDevices? My particular use case is I'm displaying data that is associated with an KTKEddystone object. If the KTKEddystone object is no longer in range, then I would also need to remove the data from the view. The only way to do this now is to check the NSSet returned for any changes?

The same way as you would do with CoreLocation [locationManager:didRangeBeacons:inRegion:](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManagerDelegate_Protocol/#//apple_ref/occ/intfm/CLLocationManagerDelegate/locationManager:didRangeBeacons:inRegion:). Just compare `NSSet` before and after update.

**Comment by jcyu0208** [comment]
Okay, so that delegate function from CoreLocation behaves the same way as the KTKEddystoneManagerDelegate counterpart, except for being called whenever the range of a beacon changes, is this correct?

**Comment by stoprocent** [comment]
@jcyu0208 yes exactly
