### ISSUE TITLE
Kontakt iOS Management App

### ISSUE THREAD

**Issue by jcyu0208** [kontaktio/kontakt-ios-sdk#14]
Hi,

In the iOS management application, once an Eddystone beacon is detected, the application is able to display its name. However, going through the KTKEddystone, I can't seem to find that property anywhere. How do we access those properties? Do we need to query the Rest API for that?

EDIT: As I understand, the KTKNearbyDevice is the one accessed in the management app. Is there any way to get the KTKEddystoneUUID from the a KTKNearbyDevice?

**Comment by stoprocent** [comment]
@jcyu0208 `KTKNearbyDevice` is a result of `KTKDevicesManager` scan. `KTKDevicesManager` was created to scan for nearby devices which can be managed (change configuration etc.).

When you are using `KTKEddystoneManager` you will get `KTKEddystone` object. It does not contain name as name is **not** a part of Eddystone specification. 

Name is included in scan response and it's a bad practice to rely on scan response. Eddystones can be set to non-connectable mode and they would not respond to scan requests from the central.

**Comment by stoprocent** [comment]
Also when using Secure Shuffling name is not even included in scan response.

**Comment by jcyu0208** [comment]
Okay thanks for clearing that up. 

One more thing, why doesn't KTKNearbyDevice include any of the Eddystone Frames? Is it because in this mode, any configurable device (even those not belonging to our organization) can be detected?

**Comment by stoprocent** [comment]
@jcyu0208 Because `KTKNearbyDevice` is an object not related to any profile. You can access Eddystone properties for `KTKNearbyDevice` by connecting and reading its configuration.

As I stated before you should **never** rely on any devices name as this is a bad practice.
