### ISSUE TITLE
See major and minor og KTKNearbyDevice

### ISSUE THREAD

**Issue by thetof91** [kontaktio/kontakt-ios-sdk#15]
Hello

How do you see the major and minor of a nearby device?
I see with how I configurate new major and minor for it.
But I want to know how do I see the Major and Minor of a iBeacon?

**Comment by stoprocent** [comment]
Hi

You should use `KTKBeaconManager` or read configuration of `KTKNearbyDevice` using `KTKDeviceConnection`.
