### ISSUE TITLE
KTKDevicesManager documentation confusion

### ISSUE THREAD

**Issue by michalciurus** [kontaktio/kontakt-ios-sdk#17]
I want to scan for Kontakt beacons and read the battery status on them.

It seems like _KTKNearbyDevice_ returns the battery status, so I followed your tutorial and used the _KTKDevicesManager_. 

One problem with the documentation is that:

1. It initializes _KTKDevicesManager_ as _KTKBluetoothManager_
2. The code doesn't compile with 1.1.3, as there's no header for _KTKBluetoothManager_

```
@property KTKDevicesManager *devicesManager;
...
self.devicesManager = [[KTKBluetoothManager alloc] initWithDelegate: self];
```
It seems like there's an error in your documentation ?

It looks like it should be: 

```
self.devicesManager = [[KTKDevicesManager alloc] initWithDelegate: self];
```

Just like in your example app.

**Comment by stoprocent** [comment]
Hi @michalciurus 

You are right! Thank you 👍 for spotting this.
