### ISSUE TITLE
KTKDevicesManager discovering is always false

### ISSUE THREAD

**Issue by michalciurus** [kontaktio/kontakt-ios-sdk#18]
Even after calling _startDevicesDiscovery_ on _KTKDevicesManager_ the _discovering_ property is always false/NO.

I've set up a breakpoint in the _didDiscoverDevices_ delegate callback -> discovering is equal to false.

http://grab.by/QhrG

**Comment by stoprocent** [comment]
@michalciurus I see you are running OSX example. Are you sure Bluetooth is ON on your Mac ?
Try implementing `devicesManagerDidFailToStartDiscovery` method from KTKDevicesManagerDelegate and see what error it's returning :)

`discovering` flag is set to `YES/true` after first call from bluetooth central so if it false it means `KTKDevicesManager` didnt get any devices from iOS

**Comment by michalciurus** [comment]
• Bluetooth is ON
• _devicesManagerDidFailToStartDiscovery_ is not called
• Manager's _centralState_ value is _PoweredOn_

Yes, that's true, I don't have any Kontakt beacons nearby - shouldn't _discovering_ still be true, as I called _startDevicesDiscovery_ ?
