### ISSUE TITLE
I recieve an error in Swift

### ISSUE THREAD

**Issue by monkki** [kontaktio/kontakt-ios-sdk#2]
i have this code and the console prints "Optional("The operation couldn’t be completed. (KTKCentralManagerErrorDomain error 10.)")"

here is my code: 
thanks in advance

import UIKit
import KontaktSDK

class ViewController: UIViewController, KTKEddystoneManagerDelegate {
    
    var eddystoneManager: KTKEddystoneManager!
    var namespaceRegion: KTKEddystoneRegion!
    var domainRegion: KTKEddystoneRegion!
    var secureNamespaceRegion: KTKSecureEddystoneRegion!
    

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        Kontakt.setAPIKey("AyxUsOijBTYrCuKkQkqofPvUlDTtEgqE")
        
        self.eddystoneManager = KTKEddystoneManager.init(delegate: self)
        
    }
    
    override func viewWillAppear(animated: Bool) {
        
        // If should scan for all nearby Eddystones
        // Passing nil will look for all regions
        self.eddystoneManager.startEddystoneDiscoveryInRegion(nil)
        
        // Scan for Eddystones with specific namespace ID
        self.namespaceRegion = KTKEddystoneRegion.init(namespaceID: "f7826da6-4fa2-4e98-8024-bc5b71e0893e")
        self.eddystoneManager.startEddystoneDiscoveryInRegion(namespaceRegion)
        
         // Scan for Eddystone with specific domain in url
        self.domainRegion = KTKEddystoneRegion.init(URLDomain: "github.com")
        self.eddystoneManager.startEddystoneDiscoveryInRegion(domainRegion)
        
        // Scan for Secure Namespace Region
        self.secureNamespaceRegion = KTKSecureEddystoneRegion.init(secureNamespaceID: "416d786e4e41")
        self.eddystoneManager.startEddystoneDiscoveryInRegion(secureNamespaceRegion)
        
    }
    
    override func viewWillDisappear(animated: Bool) {
        
        self.eddystoneManager.stopEddystoneDiscoveryInAllRegions()
        
        // ... or you can just stop for one specific region by using
        self.eddystoneManager.stopEddystoneDiscoveryInRegion(domainRegion)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    
    
    // Eddystones
    
    func eddystoneManager(manager: KTKEddystoneManager, didDiscoverEddystones eddystones: Set<KTKEddystone>, inRegion region: KTKEddystoneRegion?) {
        
        if region == self.domainRegion {
            print("Hola")
        }
        
    }

    func eddystoneManager(manager: KTKEddystoneManager, didUpdateEddystone eddystone: KTKEddystone, withFrame frameType: KTKEddystoneFrameType) {
        
    }
    
    func eddystoneManagerDidFailToStartDiscovery(manager: KTKEddystoneManager, withError error: NSError?) {
        print(error?.localizedDescription)
    }
}

**Comment by stoprocent** [comment]
Hi @monkki 

`Error code 10` is bluetooth state error. It means `state != CBCentralManagerStatePoweredOn`
Please check if bluetooth is ON and also you can have a look here [Apple Documentation](https://developer.apple.com/library/prerelease/ios/documentation/CoreBluetooth/Reference/CBCentralManager_Class/index.html#//apple_ref/c/tdef/CBCentralManagerState) to see other states.

Basically if CBCentralManager state is not `CBCentralManagerStatePoweredOn` it will return this error.
In our SDK we are waiting for state to be `.PoweredOn` before start eddystone discovery.

**Comment by stoprocent** [comment]
@monkki Can I close this issue ?

**Comment by monkki** [comment]
Yes Thanks for your time
