### ISSUE TITLE
Get a KTKDevice UUID, major and minor

### ISSUE THREAD

**Issue by sorenshg** [kontaktio/kontakt-ios-sdk#20]
Hello

I'm trying to get some iBeacon devices from the Kontakt.io Cloud. I'm using the KTKCloudClient to get the objects, but I just realized that the KTKDevice model doesn't have properties for UUID, major and minor. So how do I get the iBeacon properties from the CloudClient?

**Comment by stoprocent** [comment]
Hi @sorenshg 

Have a look at property `configuration` on `KTKDevice`. `configuration` is an instance of `KTKDeviceConfiguration` class and you will find all properties you are interested in.

**Comment by sorenshg** [comment]
Thank you for a quick answer. Next time I should open my eyes.. You can just close this issue.

**Comment by stoprocent** [comment]
@sorenshg np
