### ISSUE TITLE
Create new venue 

### ISSUE THREAD

**Issue by sgrgrsn** [kontaktio/kontakt-ios-sdk#21]
Hello there!

I would like to create a new venue in the Kontakt Cloud, and is trying to use the [createObject:completion:](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Classes/KTKCloudClient.html#//api/name/createObject:completion:) in the KTKCloudClient.

How do I specify the name and description of the venue? The name and description properties on the [KTKVenue](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Classes/KTKVenue.html) class is readonly, so I can't init a new KTKVenue object.

Right now I can do it this way, but I think it should be possible to use the createObject: method. Isn't that right?

```
NSDictionary *venueParameters = @{@"name": @"New venue",@"description":@"Created with the KontaktSDK"};

[[KTKCloudClient sharedInstance] POST:@"venue/create" parameters:venueParameters completion:^(KTKKontaktResponse * _Nullable response, NSError * _Nullable error) {

}];
```

**Comment by stoprocent** [comment]
Hi @sorenshg 

Yes you are right ... There is a missing create method for venue and actions. I will be updating SDK soon and this will be fixed. The way you are using it now is ok. 

Sorry for late reply i must have lost your issue in my notifications.

I will let you know when SDK will be updated

**Comment by sgrgrsn** [comment]
Hi again.

I need to create a new venue again, but the venueName is still readonly. Are you still planning to fix this? @stoprocent
