### ISSUE TITLE
How to output the table as csv file in kontakt-ios-sdk/Examples/OSX/Kontakt Scanner/Kontakt Scanner.xcodeproj/

### ISSUE THREAD

**Issue by yajiayang** [kontaktio/kontakt-ios-sdk#24]
Hey @stoprocent ,  I just bought 4 beacons from Kontakt and I managed to run this example kontakt scanner(kontakt-ios-sdk/Examples/OSX/Kontakt Scanner/Kontakt Scanner.xcodeproj/) Currently I can see the RSSI valueS in the app:
<img width="487" alt="screen shot 2016-08-17 at 9 11 49 pm" src="https://cloud.githubusercontent.com/assets/8527349/17761808/5a85d91c-64bf-11e6-843c-091a1ad6564d.png">
I would like to output the table to a local .csv file but I could not figure our a way to do it.  Do you have any suggestions on how should I do that? Thanks in advance for your help.

**Comment by stoprocent** [comment]
This is Swift/Obj-C question, not related to SDK ;) 
Maybe this will help http://bit.ly/2bKF2Vf
