### ISSUE TITLE
All beacons for Venue

### ISSUE THREAD

**Issue by nick-holmes** [kontaktio/kontakt-ios-sdk#25]
GET /venue/:id response specifies that there should be a property returned that includes devices for venue, but only Device Count is available as a property. Was this removed or not yet added?

I need to get the minor numbers for all beacons at a specified venue, or the lowest and the highest, and this was the only way I could think to do it.

**Comment by stoprocent** [comment]
Hi @nick-holmes 

I'm sorry for late reply I was away for some time. In fact model for venue is missing devices list. 
I'm marking this as a enhancement and I will try to include it in the next release.
I will keep you posted.
