### ISSUE TITLE
error domain error 5 on start monitoring Region on IOS 9

### ISSUE THREAD

**Issue by NorbertSzydlowski** [kontaktio/kontakt-ios-sdk#26]
I have got this issue when startMonitoringForRegion on ios 9

**Comment by stoprocent** [comment]
Can you share a bit more? Maybe code sample?

**Comment by stoprocent** [comment]
Can you share what was it ?

**Comment by NorbertSzydlowski** [comment]
This error happend when I used &#34;startMonitoringForRegion:&#34; and &#34;requestStateForRegion:&#34; one by one.  The error stopped  without code change  on the next day. I don&#39;t reproduce this issue second time.   
                
              
               
                 
                  Dnia 26 września 2016 15:58 Marek Serafin &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Can you share what was it ?
