### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by bnagarjuna** [kontaktio/kontakt-ios-sdk#28]
dyld: Library not loaded: @rpath/KontaktSDK.framework/KontaktSDK
  Referenced from: /Users/Welcome/Library/Developer/CoreSimulator/Devices/1BFA5957-3059-4430-A537-A53711E00207/data/Containers/Bundle/Application/3EAE9BD0-7C21-4B4C-B038-B61A76EDC6D5/iBeaconsInt.app/iBeaconsInt
  Reason: image not found

**Comment by stoprocent** [comment]
This is not an SDK issue. You didnt link/embed framework properly. Have a look in our README for detailed installation manual.
