### ISSUE TITLE
Estimated distance to beacon using KTKNearbyDevice

### ISSUE THREAD

**Issue by mzeeshanid** [kontaktio/kontakt-ios-sdk#29]
We are using Kontakt beacons for one of our project. Our goal is to detect user presence within 1 meter of range from beacon. So i was trying to use `KTKDevicesManager` and `KTKNearbyDevice` and it does not have any property that indicate distance/accuracy. 

I know that CLBeacon have this property but for this we have to use region monitoring. 

I think it is possible to get estimated distance for KTKNearbyDevice because both required parameters for distance calculation are there (RSSI, transmission power). How ?

**Comment by stoprocent** [comment]
Hi @mzeeshanid 

There is a method we are using internally but it was hidden for now. I will make it public starting from the next release. 
For now you can have a look [here](http://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing). `KTKNearbyDevice` have both `transmissionPower` and `RSSI` properties :)

**Comment by mzeeshanid** [comment]
Thank you for your reply. I already go through that link and used the davidgyoung's function for distance calculation. For some reason, value fluctuation is much higher.  Your internal method is using the same or you have some improved algorithm?

**Comment by stoprocent** [comment]
If you want to test it now just create a Obj-C header file and paste this:

``` Objective-C
extern double KTKCalculateDistanceFrom(int TXPower, double RSSI);
```

It will allow you to use our function.

**Comment by mzeeshanid** [comment]
What is the unit of returned value? Above mentioned function is returning very large value while my beacon is very near to the device. See the screenshot below:

<img width="808" alt="screen shot 2016-11-17 at 3 03 02 am" src="https://cloud.githubusercontent.com/assets/2767152/20367707/7a6d1dee-ac72-11e6-9425-8342986ce0af.png">

**Comment by stoprocent** [comment]
@mzeeshanid Transmission power is our transmision power level not a value itself.
Use this code for reference:
```
switch (transmissionPower) {
        case KTKDeviceTransmissionPower0: return @(-30);
        case KTKDeviceTransmissionPower1: return @(-20);
        case KTKDeviceTransmissionPower2: return @(-16);
        case KTKDeviceTransmissionPower3: return @(-12);
        case KTKDeviceTransmissionPower4: return @(-8);
        case KTKDeviceTransmissionPower5: return @(-4);
        case KTKDeviceTransmissionPower6: return @(0);
        case KTKDeviceTransmissionPower7: return @(4);
        default:  return nil;
}
```

**Comment by mechazod** [comment]
@stoprocent , how to determine the unit into meter of the very large value.

i have here value that I'm getting from CLBeacon its accurate on what I've observed.

![screen shot 2016-12-05 at 6 00 00 pm](https://cloud.githubusercontent.com/assets/16739905/20880780/788e8dcc-bb14-11e6-8027-0547277fc772.png)

**Comment by stoprocent** [comment]
Have you seen my post above?

**Comment by mechazod** [comment]
@stoprocent , got your point, but what I didn't understand of the unit of large value.

**Comment by jvanakker** [comment]
@stoprocent @mechazod 
I'm in Objective C but also getting the same (incorrect) large values when I use **KTKCalculateDistanceFrom**. And I did use a switch as mentioned above to convert the KTKDeviceTransmissionPower enum value to integer.

I also did a different distance calculation, using a formula, including a different mapping for KTKDeviceTransmissionPower0. The result seems OK, but incorrect for larger distances.

Any help with KTKCalculateDistanceFrom is appreciated.

**Comment by adrianz** [comment]
I think there was a bit of confusion regarding what arguments need to be passed into `KTKCalculateDistanceFrom`.

Rather than beacon transmission power in dBm, the first argument should represent the reference RSSI value broadcasted in the iBeacon packet. But as with every other iBeacon property, it is handled directly by the Core Location, so you don't have direct access to it. Instead, iOS uses it internally and calculates distance and proximity for you, with results available in `CLBeacon` objects.

Because of all that `KTKNearbyDevice` don't have data from the iBeacon packet, and you will need to refer to the table that shows the RSSI@1m values for each TX power level (TX power level you can get from the `KTKNearbyDevice`), available here: https://support.kontakt.io/hc/en-gb/articles/201621521 (please keep in mind these are the default values, if you have changed them, you need to use yours). Then, you can e.g. use these values in the switch that you've set up earlier.

**Comment by jvanakker** [comment]
Ok, thanks for clearing that up. However, the values for further away beacons still seem too low now. E.g. a beacon at 8 m calculates to 1.6 m.  Closer beacons (<1m) appear to have more accurate values. I know beacon distances are not too reliable, but still it seems inconsistant all the time for beacons further away.

This is the code:

`
long rssi = [nearByDevice.RSSI longValue];
KTKDeviceTransmissionPower txPower = nearByDevice.transmissionPower;
int txPower_dBm = 0;

switch (txPower)
{
    case KTKDeviceTransmissionPowerInvalid:
        break;
        
    case KTKDeviceTransmissionPower0:
        txPower_dBm = -115; // equals to -30 decimal;
        break;
    case KTKDeviceTransmissionPower1:
        txPower_dBm = -84; // equals to -20 decimal;
        break;
    case KTKDeviceTransmissionPower2:
        txPower_dBm = -81; // equals to -16 decimal;
        break;
    case KTKDeviceTransmissionPower3:
        txPower_dBm = -77; // equals to -12 decimal;
        break;
    case KTKDeviceTransmissionPower4:
        txPower_dBm = -72; // equals to -8 decimal;
        break;
    case KTKDeviceTransmissionPower5:
        txPower_dBm = -69; // equals to -4 decimal;
        break;
    case KTKDeviceTransmissionPower6:
        txPower_dBm = -65; // equals to 0 decimal;
        break;
    case KTKDeviceTransmissionPower7:
        txPower_dBm = -59; // equals to 4 decimal;
        break;
}

double distance = KTKCalculateDistanceFrom(txPower_dBm, nearByDevice.RSSI.doubleValue);
`

As an example, here's an alternative distance calculation, which seems slightly more accurate but still off for larger distances and I wonder if this should be theoretically correct:

`
double ratio_db = txPower_dBm - rssi;
//double ratio_linear = pow(10, ratio_db / (10*2)); // test
double ratio_linear = pow(10, ratio_db / (10*1));

double distanceCalc = sqrt(ratio_linear); // distanceCalc = Afstand
`

Any thoughts are welcome.

**Comment by the-unforgiven** [comment]
How can I access KTKCalculateDistanceFrom in Xamarin.iOS?

**Comment by Jul4a** [comment]
Hello, 

Im developing Android app using beacons. Can you help me, what type of beacon should I buy If I want to measure the distance between app user and beacon?

I need a beacon that know to send multiple packets at a time. And know to measure the real distance. 

 

Thank you.
