### ISSUE TITLE
Doesn't discover eddystones when iPhone in locked screen

### ISSUE THREAD

**Issue by sotrosh** [kontaktio/kontakt-ios-sdk#3]
Hello,

There is an issue I found that my application discovers properly Eddystones in foreground and background modes.
But when I lock screen on iPhone it stops discovering Eddystones

How to fix the issue above?

**Comment by stoprocent** [comment]
Hi 
Did you select `bluetooth-central` in background modes settings?
Eddystone discovery is based on CoreBluetooth so to scan in the background you need this ... [Link](https://www.dropbox.com/s/s6u3avq60wfu5r4/Screenshot%202016-02-06%2021.29.55.png?dl=0&preview=Screenshot+2016-02-06+21.29.55.png)

**Comment by sotrosh** [comment]
Yes, I set mode above but still doesn't work when locked screen

**Comment by sotrosh** [comment]
Here is my small project which uses kontak.io SDK for discovering Eddystone: https://www.dropbox.com/s/arqpa85m2y89gqu/kontakt.io.test.zip?dl=0

It work when I go to background. But when I lock screen or close application it stops working.
My Eddystones use 3.1 firmware and test on iPhone 6 with iOS 9.2.1

I hope it will help

Thank you,
Serhiy

**Comment by stoprocent** [comment]
Hi @sotrosh I will have a look today. Thanks for the code :+1:

**Comment by sotrosh** [comment]
Hi @stoprocent 
Are the any updates on current ticket?

**Comment by stoprocent** [comment]
@sotrosh I had some other more important issues to handle first. I did look through your code. It all looks good need to make few more tests tomorrow and I will let you know.

**Comment by stoprocent** [comment]
Hi @sotrosh 

I have no idea why your example behaves like you described but on my end your code works just fine and I can see logs of scanned eddystones whiule device is locked. Is your phone maybe jailbroken etc?

Im sorry but there isnt anything I can do to help with this issue. Feel free to reopen it with more details

**Comment by sotrosh** [comment]
@stoprocent thank you for reply.
No, my iPhone 6 device is not jailbroken.
It's working under iOS 9.2.1 I'll try on another device and let you know. What device and version of iOS you are using?

**Comment by stoprocent** [comment]
@sotrosh same as yours 9.2.1 but we are testing almost all versions since iOS 7.1 even tho SDK minimum supported version is 8.0

**Comment by sotrosh** [comment]
Just tried on iPod 5th generation the code above with iOS 9.1 and still doesn't work...
It works when device is active (e.g. using other apps). But when I lock screen and displays goes to sleep then it stops logging after a few seconds

**Comment by stoprocent** [comment]
This is so weird ... iOS limits background `Core Bluetooth` scanning interval but it's still scanning.

I have your code running since 45 min on few devices and they are all still logging eddystones.

Which firmware are your devices?

**Comment by stoprocent** [comment]
@sotrosh I have an idea. How many devices do you have around you at the moment?
I can see about 300 now here so maybe this is the reason.

If you have a look [here](http://stackoverflow.com/questions/20937837/corebluetooth-discovery-of-ble-peripheral-while-device-locked) there are people with similar issue while using `CoreBluetooth`.

It is related to `CBCentralManagerScanOptionAllowDuplicatesKey` flag. In the background iOS will ignore this flag and deliver multiple advertisments as one, once.

If you for example have 3+ devices around you it will scan them once and it will stop seeing new devices after few seconds. 

You can verify if im right by starting your application with beacons turned off (take off the battery), locking yopur screen and putting battery back in :)

Let me know what are the results...

**Comment by sotrosh** [comment]
I have one Eddystone in my room. @stoprocent I added CBCentralManagerScanOptionAllowDuplicatesKey into Info.plist file and got the same behavior: doesn't work when lock screen...
Here is updated project with added key: https://www.dropbox.com/s/pj735dtfj1ybplq/kontakt.io.test.zip?dl=0

**Comment by stoprocent** [comment]
@sotrosh CBCentralManagerScanOptionAllowDuplicatesKey is a `CoreBluetooth` scanning options key not `Info.plist`. I have tried your example with just 2 beacons around and it behaves exactly like you have described and it will be correct in such a situation. Try with a scenario I have described above and you will see.

**Comment by sotrosh** [comment]
@stoprocent 
Is it possible to set `CBCentralManagerScanOptionAllowDuplicatesKey` key with Kontakt.io SDK?
Sorry but I slightly confused... As I understand with setting `CBCentralManagerScanOptionAllowDuplicatesKey` it should work in background even when iPhone device lock screen or application is closed?

My case is that some venue will have one Eddystone only which is placed near the door.
It should work when users installed our application and just go near venue they should receive push notification even when they don't touch device (when screen is locked).

Will this case work with Eddystone and Kontakt.io SDK? If so what I'm doing wrong?

P.S. With Apple iBeacon it works well even when locked screen or app is closed.

Thank you,
Serhiy

**Comment by stoprocent** [comment]
`CBCentralManagerScanOptionAllowDuplicatesKey` is used by the `Kontakt.io iOS SDK`.
Problem you having is related to the fact that when CoreBluetooth is scanning in the background iOS will ignore `CBCentralManagerScanOptionAllowDuplicatesKey` value and set it by default to `NO`. So always one bluetooth device will be scanned just once.

It's better to use iBeacon profile in your case as iBeacon have much better support on iOS. It's native and Eddystone is not. Eddystone scanner is using `CoreBluetooth`. iBeacon is using CoreLocation
