### ISSUE TITLE
No delegate methods gets called . 

### ISSUE THREAD

**Issue by NavdeepWahra** [kontaktio/kontakt-ios-sdk#30]
Hi 
I am integrating your sdk to one of my project . I have followed the instruction provided on the website . 
Here is my code snippet
-------------------------------------------------------------------------------------------------
    KTKBeaconManager *beaconManager = [[KTKBeaconManager alloc] initWithDelegate:self];
    NSUUID *uid = [[NSUUID alloc] initWithUUIDString:@"f7826da6-4fa2-4e98-8024-bc5b71e0893e"];
    
    KTKBeaconRegion *beaconRegion = [[KTKBeaconRegion alloc] initWithProximityUUID:uid identifier:@"com.domnique.beaconDemo"];

  switch ([KTKBeaconManager locationAuthorizationStatus]) {
        
        case kCLAuthorizationStatusNotDetermined:
            [beaconManager requestLocationAlwaysAuthorization];
            break;
        case kCLAuthorizationStatusDenied:
            NSLog(@"Denied");
            break;
        case kCLAuthorizationStatusRestricted:
            NSLog(@"Restricted");
            break;
        case kCLAuthorizationStatusAuthorizedWhenInUse:
            NSLog(@"in Use");
            break;
        case kCLAuthorizationStatusAuthorizedAlways:
            
            if ([KTKBeaconManager isMonitoringAvailable]) {
                
                [beaconManager startMonitoringForRegion:beaconRegion];
            }
            break;
            
        default:
            break;
    }
----------------------------------------------------------------------------------------------

Problem with me is that after asking permission for location , no delegate call backs . And even the app is also not get listed in location service for using location .

I have added the key in info.plist for locationServiceAlways. 

P.S - This is the version i am using right now 
//  KontaktSDK
//  Version: 1.3.2

Kindly revert .

**Comment by patricks** [comment]
Are you calling `requestStateForRegion` in your code. I have some problems, if I call this method.

**Comment by NavdeepWahra** [comment]
No i am not calling this method . I am just calling the override requestLocationAlwaysAuthorization
method .
Below is my snippet .

 KTKBeaconManager *beaconManager = [[KTKBeaconManager alloc] initWithDelegate:self];
        
    NSUUID *uid = [[NSUUID alloc] initWithUUIDString:@"f7826da6-4fa2-4e98-8024-bc5b71e0893e"];
    
    KTKBeaconRegion *beaconRegion = [[KTKBeaconRegion alloc] initWithProximityUUID:uid identifier:@"TmNq"];
    
    
    
    switch ([KTKBeaconManager locationAuthorizationStatus]) {
        
        case kCLAuthorizationStatusNotDetermined:
            [beaconManager requestLocationAlwaysAuthorization];
            break;
        case kCLAuthorizationStatusDenied:
            NSLog(@"Denied");
            break;
        case kCLAuthorizationStatusRestricted:
            NSLog(@"Restricted");
            break;
        case kCLAuthorizationStatusAuthorizedWhenInUse:
            NSLog(@"in Use");
            break;
        case kCLAuthorizationStatusAuthorizedAlways:
            
            if ([KTKBeaconManager isMonitoringAvailable]) {
                
                [beaconManager startMonitoringForRegion:beaconRegion];
            }
            break;
            
        default:
            break;
    }

**Comment by stoprocent** [comment]
Hi @NavdeepWahra 

Did you add correct keys to your `Info.plist` file? Have a look here https://developer.kontakt.io/ios-sdk/quickstart/installation/#first-steps-after-installation

If yes then can you try calling code below before the switch. Calling `requestLocationAlwaysAuthorization` multiple times will not result in any issues.
``` Objective-C
[beaconManager requestLocationAlwaysAuthorization];
```

**Comment by Sea-Eagle** [comment]
Even doing above changes still Delegate methods are unable to triggered. But when I uninstall and install my app again its working but once installed one or two times delegate methods are calling

**Comment by stoprocent** [comment]
Sorry @Sea-Eagle I don't understand. Can you maybe share your code?

**Comment by Sea-Eagle** [comment]
`#pragma mark bluetooth status

-(void)beaconScanStart{
    NSLog(@"beaconScanStart ");
    //Kontakt Beacon API Key setting
    [Kontakt setAPIKey:KONTAKTAPIKEY];
    self.beaconManager = [[KTKBeaconManager alloc] initWithDelegate:self];
    self.beaconManager.delegate = self;
    [self.beaconManager requestLocationAlwaysAuthorization];
    switch ([KTKBeaconManager locationAuthorizationStatus]) {
        case kCLAuthorizationStatusNotDetermined:
            [self.beaconManager requestLocationAlwaysAuthorization];
            break;
        case kCLAuthorizationStatusDenied:
        case kCLAuthorizationStatusRestricted:
            // No access to Location Services
            break;
            
        case kCLAuthorizationStatusAuthorizedWhenInUse:
            if ([KTKBeaconManager isMonitoringAvailable]) {
                NSUUID *myProximityUUID = [[NSUUID alloc] initWithUUIDString:@"*****************"];
                KTKBeaconRegion *region1 = [[KTKBeaconRegion alloc] initWithProximityUUID:myProximityUUID identifier:@"Beacon region 1"];
                
                [self.beaconManager startMonitoringForRegion:region1];
            }
            // For most iBeacon-based app this type of
            // permission is not adequate
            break;
            
        case kCLAuthorizationStatusAuthorizedAlways:
            // We will use this later
            break;
    }  
}
-(void)centralManagerDidUpdateState:(CBCentralManager *)central{
    NSLog(@"Central status %ld",(long)[central state]);
    
    if(central.state == CBManagerStatePoweredOff){
        NSLog(@"status is CBManagerStatePoweredOff");
        
        UIAlertController* alert = [UIAlertController alertControllerWithTitle:@"Bluetooth" message:@"Please SwitchOn Bluetooth" preferredStyle:UIAlertControllerStyleAlert];
        
        [bluetoothWindow makeKeyAndVisible];
        [bluetoothWindow.rootViewController presentViewController:alert animated:YES completion:nil];
 //       [self.locationManager stopMonitoringForRegion:self.gofindoBeaconRegion];
        
    }
    if(central.state == CBManagerStatePoweredOn){
        NSLog(@"status is CBManagerStatePoweredOn");
        bluetoothWindow.hidden = YES;
        NSUUID *myProximityUUID = [[NSUUID alloc] initWithUUIDString:@"***************"];
        KTKBeaconRegion *region1 = [[KTKBeaconRegion alloc] initWithProximityUUID:myProximityUUID identifier:@"Beacon region 1"];
        if ([KTKBeaconManager isMonitoringAvailable]) {
            NSLog(@"isMonitoringAvailable");

            [self.beaconManager startMonitoringForRegion:region1];
        }

    }
    
}

- (void)beaconManager:(KTKBeaconManager *)manager didChangeLocationAuthorizationStatus:(CLAuthorizationStatus)status {
    if (status == kCLAuthorizationStatusAuthorizedAlways) {
        NSLog(@"didChangeLocationAuthorizationStatus");
        NSUUID *myProximityUUID = [[NSUUID alloc] initWithUUIDString:@"********************"];
        KTKBeaconRegion *region1 = [[KTKBeaconRegion alloc] initWithProximityUUID:myProximityUUID identifier:@"Beacon region 1"];
        if ([KTKBeaconManager isMonitoringAvailable]) {
            [self.beaconManager startMonitoringForRegion:region1];
        }
    }
}
- (void)beaconManager:(KTKBeaconManager *)manager didStartMonitoringForRegion:(__kindof KTKBeaconRegion *)region {
    // Do something when monitoring for a particular
    // region is successfully initiated
    NSLog(@"didStartMonitoringForRegion %@",region);
    [manager startRangingBeaconsInRegion:region];
}
-(void)beaconManager:(KTKBeaconManager *)manager rangingBeaconsDidFailForRegion:(__kindof KTKBeaconRegion *)region withError:(NSError *)error{
    NSLog(@"rangingBeaconsDidFailForRegion %@",error);
}
-(void)beaconManager:(KTKBeaconManager *)manager didDetermineState:(CLRegionState)state forRegion:(__kindof KTKBeaconRegion *)region{
    NSLog(@"didDetermineState %ld region %@",(long)state,region);
}
- (void)beaconManager:(KTKBeaconManager *)manager monitoringDidFailForRegion:(__kindof KTKBeaconRegion *)region withError:(NSError *)error {
    // Handle monitoring failing to start for your region
    NSLog(@"monitoringDidFailForRegion %@",error);
}

- (void)beaconManager:(KTKBeaconManager *)manager didEnterRegion:(__kindof KTKBeaconRegion *)region {
    // Decide what to do when a user enters a range of your region; usually used
    // for triggering a local notification and/or starting a beacon ranging
     [manager startRangingBeaconsInRegion:region];
    NSLog(@"didEnterRegion %@",region);
}

- (void)beaconManager:(KTKBeaconManager *)manager didExitRegion:(__kindof KTKBeaconRegion *)region {
    // Decide what to do when a user exits a range of your region; usually used
    // for triggering a local notification and stoping a beacon ranging
     [manager stopMonitoringForRegion:region];
    NSLog(@"didExitRegion %@",region);
}
-(void)beaconManager:(KTKBeaconManager *)manager didRangeBeacons:(NSArray<CLBeacon *> *)beacons inRegion:(__kindof KTKBeaconRegion *)region{
    NSLog(@"didRangeBeacons %@",beacons);
    NSLog(@"Beacons count %lu",(unsigned long)[beacons count]);
    NSLog(@"Proximity %ld",(long)[[beacons lastObject] proximity]);
    NSLog(@"last beacon %@",[beacons lastObject]);
}
`

**Comment by Sea-Eagle** [comment]
This is my code I'm calling "beaconScanStart()" from 
 `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    [self beaconScanStart];
  
    return YES;
}`
When i have installed app in my iPhone 5S for the first time it is able to range beacons but when I stop the running the app and without uninstalling if i run the app from xcode it is unable to beaconmanager delegate methods

**Comment by Sea-Eagle** [comment]
@stoprocent 

Can you check my code 
AppDelegate.h
`
#import <UIKit/UIKit.h>
#import <KontaktSDK/KontaktSDK.h>

#define IS_OS_8_OR_LATER ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0)


@interface AppDelegate : UIResponder <UIApplicationDelegate,KTKBeaconManagerDelegate>

@property (strong, nonatomic) UIWindow *window;
@property(strong,nonatomic) KTKBeaconManager *beaconManager;

@end

`
AppDelegate.m
`
#import "AppDelegate.h"

@interface AppDelegate ()
@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
//    self.locationManger = [[CLLocationManager alloc] init];
//    self.locationManger.desiredAccuracy = kCLLocationAccuracyBest;
//    [self.locationManger setDelegate:self];
//    [self.locationManger startUpdatingLocation];

    [Kontakt setAPIKey:@"*****************"];
    
    [self beaconScan];

    return YES;
}


- (void)applicationWillResignActive:(UIApplication *)application {
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
}


- (void)applicationDidEnterBackground:(UIApplication *)application {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
}


- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
}


- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
}


- (void)applicationWillTerminate:(UIApplication *)application {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
}

-(void)beaconScan{
    NSLog(@"beaconScan");
    
//    if(IS_OS_8_OR_LATER){
//        NSUInteger code = [CLLocationManager authorizationStatus];
//        if (code == kCLAuthorizationStatusNotDetermined && ([self.locationManger respondsToSelector:@selector(requestAlwaysAuthorization)] || [self.locationManger respondsToSelector:@selector(requestWhenInUseAuthorization)])) {
//            // choose one request according to your business.
//            if([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"]){
//                [self.locationManger requestAlwaysAuthorization];
//            } else {
//                NSLog(@"Info.plist does not contain NSLocationAlwaysUsageDescription or NSLocationWhenInUseUsageDescription");
//            }
//        }
//    }
//    
//    [self.locationManger requestAlwaysAuthorization];
//    
//    [self.locationManger startUpdatingLocation];
    
    self.beaconManager = [[KTKBeaconManager alloc] initWithDelegate:self];
    
    NSUUID *myProximityUUID = [[NSUUID alloc] initWithUUIDString:@"*************"];
    KTKBeaconRegion *region1 = [[KTKBeaconRegion alloc] initWithProximityUUID:myProximityUUID identifier:@"Beacon region 1"];

    switch ([KTKBeaconManager locationAuthorizationStatus]) {
        case kCLAuthorizationStatusNotDetermined:
            [self.beaconManager requestLocationAlwaysAuthorization];
            break;
            
        case kCLAuthorizationStatusDenied:
        case kCLAuthorizationStatusRestricted:
            // No access to Location Services
            break;
            
        case kCLAuthorizationStatusAuthorizedWhenInUse:
            // For most iBeacon-based app this type of
            // permission is not adequate
            break;
            
        case kCLAuthorizationStatusAuthorizedAlways:
            if ([KTKBeaconManager isMonitoringAvailable]) {
                NSLog(@"kCLAuthorizationStatusAuthorizedAlways");
                [self.beaconManager startMonitoringForRegion:region1];
            }
            break;
    }
    
}
- (void)beaconManager:(KTKBeaconManager *)manager didChangeLocationAuthorizationStatus:(CLAuthorizationStatus)status {
    if (status == kCLAuthorizationStatusAuthorizedAlways) {
        NSUUID *myProximityUUID = [[NSUUID alloc] initWithUUIDString:@"****************"];
        KTKBeaconRegion *region1 = [[KTKBeaconRegion alloc] initWithProximityUUID:myProximityUUID identifier:@"Beacon region 1"];
        [self.beaconManager startMonitoringForRegion:region1];
    }else if (status == kCLAuthorizationStatusNotDetermined){
        [self.beaconManager requestLocationAlwaysAuthorization];
    }
}
- (void)beaconManager:(KTKBeaconManager *)manager didStartMonitoringForRegion:(__kindof KTKBeaconRegion *)region {
    // Do something when monitoring for a particular
    // region is successfully initiated
    NSLog(@"didStartMonitoringForRegion %@",region);
    [manager startRangingBeaconsInRegion:region];
}

- (void)beaconManager:(KTKBeaconManager *)manager monitoringDidFailForRegion:(__kindof KTKBeaconRegion *)region withError:(NSError *)error {
    NSLog(@"monitoringDidFailForRegion %@ %@error ",region,error);
}

- (void)beaconManager:(KTKBeaconManager *)manager didEnterRegion:(__kindof KTKBeaconRegion *)region {

    NSLog(@"didStartMonitoringForRegion %@",region);

    [manager startRangingBeaconsInRegion:region];
}

- (void)beaconManager:(KTKBeaconManager *)manager didExitRegion:(__kindof KTKBeaconRegion *)region {

    NSLog(@"didStartMonitoringForRegion %@",region);

    [manager stopRangingBeaconsInRegion:region];
}
-(void)beaconManager:(KTKBeaconManager *)manager didRangeBeacons:(NSArray<CLBeacon *> *)beacons inRegion:(__kindof KTKBeaconRegion *)region{
    NSLog(@"didRangeBeacons beacons %@ in region %@",beacons,region);
}
@end
`
