### ISSUE TITLE
@import directive does not work with Obj-c++

### ISSUE THREAD

**Issue by moimart** [kontaktio/kontakt-ios-sdk#32]
Hi,

`@import` directive in framework headers don't allow the usage of the framework to be behind an obj-c++ implementation. 

It is very easy to fix either by not using the `@import` directive or by doing it with this example code:
```
#if __has_feature(modules)
@import CoreLocation;
#else
#import <CoreLocation/CoreLocation.h>
#endif
```
Additionally, I'm not sure if the #ifdef for testing iOS 10 CoreBluetooth types is working well with iOS 10.1. At least, I had to disable it in my system but I didn't have a go to actually fix it.

Thanks!

Br,
Moises

**Comment by stoprocent** [comment]
Hi @moimart 
I will have a look at your comments next week. So keeping this issue opened 👍

**Comment by Rastaman72** [comment]
Hello 
In Xcode 9 when i try to use your library with obj-c project i got plenty errors about @import.
Please fix it.

**Comment by stoprocent** [comment]
Hi @Rastaman72. I've created an empty Objective-C project and included our SDK using Cocoapods and another with manual SDK installation and I see no warning in Xcode 8 and Xcode 9. 
Can you provide me with sample project or more info so I can help ?
