### ISSUE TITLE
Monitoring starts but no region is entered (Admin app works flawlessly)

### ISSUE THREAD

**Issue by moimart** [kontaktio/kontakt-ios-sdk#33]
Hi,

I'm using objective-C and I'm able to start monitoring for a region (`didStartMonitoringForRegion` is called). However, I don't get any callbacks for entering/exiting a region -- even though, the beacons are very close. Any idea on what could be happening?

Thanks!

Br,
Moises

**Comment by moimart** [comment]
I don't have any problems seeing the beacons with CLLocationManager, though. Pretty much the same implementation as using Kontakt's wrapper.

**Comment by stoprocent** [comment]
Hi @moimart 

Have a look here https://support.kontakt.io/hc/en-gb/articles/207297430-didEnterRegion-method-not-being-called-
And let me know if it helps.

**Comment by stoprocent** [comment]
Hi @moimart  
If this issue still needs some attention please feel free to reopen it.
