### ISSUE TITLE
Monitoring & state detection not working with some identifiers

### ISSUE THREAD

**Issue by michalkalis** [kontaktio/kontakt-ios-sdk#34]
Hey,

I've been struggling with getting my `KTKBeaconManagerDelegate`s methods called, I did everything as suggested in your GitHub README, your guide, I triple-checked everything and still couldn't find a cause for the issue.

So to make it short, when instantiating `KTKBeaconRegion` I provided an identifier `Michal`, with capital "M". After changing it to basically anything with first lowercase character, everything started working as expected.

Can you reproduce the issue? Is there really some magic that doesn't accept initial capital characters? Or have I missed something?

Thanks!
Michal

**Comment by stoprocent** [comment]
Hi @michalkalis I will try to reproduce it and I will let you know if I find anything. For now i can't think of anything.

**Comment by stoprocent** [comment]
@adrianz Can you please help with reproducing this issue ?

**Comment by adrianz** [comment]
@stoprocent I've tried creating regions with different identifiers, starting with upper case and lower case letters (including `Michal` and `michal`) as well as identifiers only made of upper or lower case letters, numbers, emoji, etc. – in all cases region monitoring and beacon ranging inside those regions worked as expected. All test were repeated with regions made of Proximity UUID, Proximity UUID and Major, and Proximity UUID, Major and Minor with the same result. Tests were conducted on iPhone 6S with iOS 10.1.1 and latest stable SDK (1.3.2).

@michalkalis Can you provide a bit more details about your implementation, perhaps a sample project that would allow us to reproduce this issue?

**Comment by melbic** [comment]
Hey, I had the same issue where `beaconManager: didDetermineState: forRegion:` wasn't called when working with the `KTKBeaconManager`. When implementing it directly with  the `CLLocationManager` the delegate method was always called. 
Now, because I didn't wanna use some special identifier, I just used `[proximityUUID UUIDString] ` as identifier. 

Beside of that it isn't working with the Kontakt SDK, is it a bad practice?

**Comment by stoprocent** [comment]
Is it still valid? Closing for now due to inactivity.
