### ISSUE TITLE
Beacon Pros in iOS not firing Enter/Exit events

### ISSUE THREAD

**Issue by teemnam** [kontaktio/kontakt-ios-sdk#35]
I have beacon pros using iOS app and they are not firing the Enter/Exit events. My code for Enter/Exit work for all other beacon types from Kontakt but beacon pros are not getting detected. I got the region based enter/exit but not getting the specific to beacon.

**Comment by stoprocent** [comment]
Hi 
I belive this issue is a duplicate of your ticket with our support on zendesk.
Closing :)
