### ISSUE TITLE
Kontakt iOS SDK(8) - Region Failed

### ISSUE THREAD

**Issue by pdichone** [kontaktio/kontakt-ios-sdk#36]
Hi there,

I am trying to get an iOS app going that connects to the kontakt beacons.  I have one and have gone through the setting up documentation, but I can't seem to figure out how to detect the beacon or enter the region specified.

`func beaconManager(_ manager: KTKBeaconManager, monitoringDidFailFor region: KTKBeaconRegion?, withError error: Error?) {
        print("Region Failed \(error!.localizedDescription)")
    }
`
It always fails and returns a "Could not resolve proximity"

Any help, guidance is highly appreciated.

Thank you

**Comment by stoprocent** [comment]
Hi @pdichone 

Have a look here at our sample code: https://github.com/kontaktio/kontakt-ios-sdk-workshop
Method you have provided means nothing without more context.
Please feel free to reopen this issue if needed
