### ISSUE TITLE
bicode not recognized yet

### ISSUE THREAD

**Issue by beniaminorossini** [kontaktio/kontakt-ios-sdk#4]
Hi, after 1.0.3 upgradig, archive generator in xcode not recognize yet bitcode.

My error in detail:

ld: '/Users/manuel/x-code/bfm/Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib.a(GTMNSData+zlib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

thx

**Comment by stoprocent** [comment]
Hi, It's known issue and I will publish new version today in few hours

**Comment by stoprocent** [comment]
Ups... Just noticed now. 
There is a similar issue with bitcode on KontaktSDK but ur error is regarding Google Libraries :)

**Comment by beniaminorossini** [comment]
Sorry, noticed me too now!! i've got same problem with kontaktio sdk on friday and i tought that  was the same.
Sorry again and thx

**Comment by stoprocent** [comment]
No problem :) Happy to help. Still there is an issue with KontaktSDK when submiting to AppStore with **include symbols** option. Im working now to automate including `*.bcsymbolmap` files.
