### ISSUE TITLE
Problems kontakt.io SDK and geofences in one project.

### ISSUE THREAD

**Issue by patricks** [kontaktio/kontakt-ios-sdk#40]
# kontaktio_geofencing_problem

If there is a ```CLLocationManager``` (Geofences) and a ```KTKBeaconManager``` (iBeacons) running in the same Swift project, the ```KTKBeaconManagerDelegate``` sometimes tries to handle a ```CLCircularRegion```.  
If I try to access the ```proximityUUID``` from the ```KTKBeaconRegion``` object in the methods ```didDetermineState:```, ```didEnter:``` or ```didExitRegion:``` I get the following error:  
```swift
libswiftFoundation.dylib`static Foundation.UUID._unconditionallyBridgeFromObjectiveC (Swift.Optional<__ObjC.NSUUID>) -> Foundation.UUID:
```

I have build a demo project to proof this.

[https://github.com/patricks/kontaktio_geofencing_problem](https://github.com/patricks/kontaktio_geofencing_problem)

**Comment by stoprocent** [comment]
Hi @patricks 

Yes I'm aware about this issue.  I will report here when it's fixed. I will try to patch it this/next week.

**Comment by patricks** [comment]
I have updated to the latest to SDK version 1.4.1 but I have the same problem. Should this update fix this bug?

**Comment by stoprocent** [comment]
@patricks not yet. This is a bigger task as it touches many places in the SDK.
I'm already working on the solution but I can't give you specific dates now.

**Comment by stoprocent** [comment]
@patricks can you report if `1.4.2` fixed your issue ?

**Comment by patricks** [comment]
Yes, tried it on 2 different projects, now it works fine. Thx 👍

**Comment by fboxleit** [comment]
I got the same Problem although I'm using 1.4.2. Do you have any Tips or Workarounds for me to fix this?

**Comment by patricks** [comment]
I have bad news, the problem still exists, it happens less often, but it still exists. The problem is that I can't reproduce it on purpose. 

@stoprocent do you have any new or further information on the problem?

**Comment by stoprocent** [comment]
@patricks I will try to create sample project and debug it more. I will keep you posted
