### ISSUE TITLE
Hello,i send insider@kontakt.io an email for help,but no response.

### ISSUE THREAD

**Issue by zhoupIT** [kontaktio/kontakt-ios-sdk#42]
I bought your gateway equipment, it even after the Internet, I can see it in the background to scan the beacon, i can see the data, but I now want to use Android or Apple to get these scanned beacon data, how to get?Is there a demo?

**Comment by adrianz** [comment]
Hi @zhoupIT 

Issues sections are meant for reporting bugs in our products. If you need help, please check our documentation in the [Developer Portal](https://developer.kontakt.io). You might be particularly interested in this guide: https://developer.kontakt.io/rest-api/api-guides/location-engine-monitoring/

**Comment by zhoupIT** [comment]
But i did not found the api which can solve the problem,and i email you,but got not reponse?You just tell me to see the website,i want to tell you i saw the website.

**Comment by andywith** [comment]
@zhoupIT 有些关于kontakt开发想问问您
