### ISSUE TITLE
Get more results

### ISSUE THREAD

**Issue by zhoupIT** [kontaktio/kontakt-ios-sdk#43]
Hello there!
```objc
[[KTKCloudClient sharedInstance] getObjects:[KTKDevice class] parameters:@{@"uniqueId":@"b05C6"} completion:^(KTKKontaktResponse * _Nullable response, NSError * _Nullable error) {
        NSLog(@"%@ ",response);   
    }];
```
I have used the method getObjects to get my gateway devices,and your tips tell me I can get more results when use the following example,but i found the value of response.nextResultsURL is nil.It will cause an error "unsupported URL".
```objc
// Call next result set ..
        [[KTKCloudClient sharedInstance] GET:response.nextResultsURL completion:^(KTKKontaktResponse * _Nullable response, NSError * _Nullable error) {
            // ... more results ?
        }];
```

**Comment by stoprocent** [comment]
Hi @zhoupIT 

`nextResultsURL` will contain a link to more results but only if there are more results. Otherwise is `nil`. 

If you are running query like you posted above with parameters: `@{@"uniqueId":@"b05C6"}` you are asking for one particular beacon so there will be no more results.
