### ISSUE TITLE
respoons contacts is null

### ISSUE THREAD

**Issue by andywith** [kontaktio/kontakt-ios-sdk#44]
**curl post**

curl -X "GET" "https://ovs.kontakt.io/presence/contact/receiver?placeId=xxxxxxxxxxx&interval=M1&startTimestamp=1489631400&endTimestamp=1489631491&q=properties.accessLevel==4" \
     -H "Api-Key: xxxxxxxxxxxxx" \
     -H "Accept: application/vnd.com.kontakt+json;version=9"

**respoons contacts is null**

{"searchMeta":{"interval":"M1","placeId":"xxxxxxxx","startTimestamp":1489631400,"endTimestamp":1489631491,"startIndex":0,"maxResult":500,"prevResults":"","nextResults":"https://ovs.kontakt.io/presence/contact/receiver?placeId=xxxxxxxxxxxxxx&interval=M1&startTimestamp=1489631400&endTimestamp=1489631491&q=properties.accessLevel%3D%3D4&startIndex=500","filter":"properties.accessLevel==4"},"contacts":[]}

**Comment by stoprocent** [comment]
Hi 

This issue is not related to our iOS SDK. You should look for support here https://developer.kontakt.io/rest-api/api-guides/quickstart/ and if you still have any issues please feel free to submit support ticket here https://support.kontakt.io/hc/en-gb/requests/new
