### ISSUE TITLE
Why is connection to beacons necessary for Kontakt.io specific data like uniqueId?

### ISSUE THREAD

**Issue by Andruschenko** [kontaktio/kontakt-ios-sdk#47]
In the android version of the SDK, Kontakt.io specific fields like `uniqueId`, `batteryLevel` etc. are sent alongside the iBeacon specific fields like uuid, major, minor, accuracy etc. in the `onIBeaconsUpdated` event without a need to start a connection to the beacon (which requires the device to be connected to the internet) for the Kontakt.io specific fields.

In the iOS version, when I want to receive e.g. the uniqueId AND the uuid of the beacon, I have to start a KTKDeviceConnection which requires an internet connection of the device and is more power consuming. Why is this necessary on iOS and not necessary on Android?

This seems to be an issue with quite some people since the issues #19 , #20 and #15 which I looked at are related to this question.

Thanks!

**Comment by adrianz** [comment]
iOS has a slightly different architecture than Android. iBeacon packets (that contain Proximity UUID, Major and Minor) on iOS are handled exclusively by Core Location. `KTKBeaconManager` is based on the APIs.

iBeacon standard does not have a place for manufacturer specific data (like our Unique ID, battery levels, etc.) so they are available in [different](https://support.kontakt.io/hc/en-gb/articles/201492522) [packets](https://support.kontakt.io/hc/en-gb/articles/206543744). These additional packets are readable via Core Bluetooth and that's what `KTKDevicesManager` uses.

Unfortunately iOS, unlike Android, doesn't gives us a way to know that these packets come from the same device.

Please keep in mind that Unique ID is meant only for beacon management. In end user applications, when you want to monitor and range beacons, you should rely on the iBeacon identifiers alone, so you can take advantage of the way iOS handles iBeacons (background region monitoring basically with no battery impact, being able to wake up your app on region boundaries crossing, etc.).

**Comment by Andruschenko** [comment]
Thanks for your prompt reply and the detailed explanation.
