### ISSUE TITLE
KTKDevicesManagerDelegate Nullability

### ISSUE THREAD

**Issue by robcadwallader** [kontaktio/kontakt-ios-sdk#48]
In `KTKDevicesManager`'s `didDiscoverDevices` method, `devices` is marked `_Nullable`. The documentation does not explain why this parameter could be `nil`. That is, it is unclear why `didDiscoverDevices` would ever be called without discovered devices.

Similarly, the `devicesManagerDidFailToStartDiscovery:withError:` method marks `error` `_Nullable`. The documentation does not specify the circumstances under which this method would be called with a `nil` `error` parameter.

The use cases of both of these methods imply to me that the aforementioned parameters should never be `nil`. If that is true, they should be marked `_Nonnull`. If there are cases that I am overlooking, then the documentation should be updated to explain those cases.

**Comment by stoprocent** [comment]
@robcadwallader this has been resolved with `1.5.1` update. Closing ...
