### ISSUE TITLE
Unable to run project with SDK dependancy

### ISSUE THREAD

**Issue by greencoppercompany** [kontaktio/kontakt-ios-sdk#5]
Hi,

Trying to integrate the latest SDK, but got an error during app launching (either simulator or device):

dyld: Library not loaded: @rpath/KontaktSDK.framework/KontaktSDK
  Referenced from: /var/mobile/Containers/Bundle/Application/5E332836-5379-48C4-96BD-4F0D7AC4C86D/goevent.app/goevent
  Reason: image not found

I saw some commits friday and this morning, is it related?
Thanks.

Loïc

**Comment by greencoppercompany** [comment]
It was working on a fresh project. Bug was due to my project, sorry for bugging!

**Comment by stoprocent** [comment]
No worries. Here to help :)
