### ISSUE TITLE
 "didRangeBeacons" results empty array

### ISSUE THREAD

**Issue by Sea-Eagle** [kontaktio/kontakt-ios-sdk#50]
Hi, Team

I'm using Kontakt.io sdk in my app. when I'm ranging beacon always I'm getting empty array even beacon immediate to device.

`
    NSUUID *ProximityUUID = [[NSUUID alloc] initWithUUIDString:@"7244bebc-0084-4605-baef-0592ec35d589"];
    self.KTKBRegion = [[KTKBeaconRegion alloc] initWithProximityUUID:ProximityUUID identifier:@"Beacon"];
    self.KTKBManager = [[KTKBeaconManager alloc] initWithDelegate:self];
[self startMonitoring];

-(void)startMonitoring{    
    NSLog(@"Entered to start monitoring method");
    
    if ([[self.KTKBManager monitoredRegions] containsObject:self.KTKBRegion]) {
        NSLog(@"this beacon region is already monitored %@",self.KTKBRegion.proximityUUID);
        [self.KTKBManager requestStateForRegion:self.KTKBRegion];
        
    } else {
        
        NSLog(@"this beacon region is not monitored till %@ ",self.KTKBRegion.proximityUUID);
        [self.KTKBManager startMonitoringForRegion:self.KTKBRegion];
    }
    
}

//Beacon Monitoring method
-(void)beaconManager:(KTKBeaconManager *)manager didStartMonitoringForRegion:(__kindof KTKBeaconRegion *)region{
    NSLog(@"Beacon Monitoring Started for the region %@",region.proximityUUID);
    [self.KTKBManager startRangingBeaconsInRegion:self.KTKBRegion];
}
//
-(void)beaconManager:(KTKBeaconManager *)manager didDetermineState:(CLRegionState)state forRegion:(__kindof KTKBeaconRegion *)region{
    NSLog(@"Beacon Region State Determine ");
    
    switch (state) {
        case CLRegionStateUnknown:
        {
            NSLog(@"Region state is unknown");
            [self.KTKBManager stopRangingBeaconsInRegion:self.KTKBRegion];
            break;
        }
        case CLRegionStateInside:
        {
            NSLog(@"Region state is In-Side");
            [self.KTKBManager startRangingBeaconsInRegion:self.KTKBRegion];
            break;
        }
        case CLRegionStateOutside:
        {
            NSLog(@"Region state is Out-Side");
            [self.KTKBManager stopRangingBeaconsInRegion:self.KTKBRegion];
            break;
        }
    }
}

-(void)beaconManager:(KTKBeaconManager *)manager didRangeBeacons:(NSArray<CLBeacon *> *)beacons inRegion:(__kindof KTKBeaconRegion *)region{
    
      NSLog(@"we have ranged beacon %@ proximityUUID %@",beacons,region.proximityUUID);
}    
`

**Comment by stoprocent** [comment]
@Sea-Eagle is it still valid? Closing for now due to inactivity.

**Comment by Sea-Eagle** [comment]
Yes still I'm facing issue
