### ISSUE TITLE
Can bluetooth turn on and off event wake the app when app is terminated(killed)

### ISSUE THREAD

**Issue by paultnp** [kontaktio/kontakt-ios-sdk#51]
I am using kontakt-ios-sdk with kontakt beacons. I am able to wake up the app and show local notification(or do some activity) when I enter in or exit from the beacon range while app is in terminated (killed) state.

I have a condition that my iPhone is in terminated (killed) state and bluetooth is turned off. Now a new beacon comes in the range (which was not in the range earlier) and I turn on the bluetooth without moving the iPhone. How will I detect that new beacon is in range.

Any help would be appreciated.

Thanks

**Comment by stoprocent** [comment]
@paultnp is this still valid? I don't think there is anything you can do with current iOS limitations.
Unless your app is in the foreground. You can try playing with [requestStateForRegion:](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Classes/KTKBeaconManager.html#//api/name/requestStateForRegion:) method. 

Just to make sure you are talking about an event when bluetooth is OFF and app is terminated and you walk into a region and enable Bluetooth? Can you try this scenario with `notifyEntryStateOnDisplay` set to `true/YES` on `KTKBeaconRegion` object?
