### ISSUE TITLE
beaconManager:monitoringDidFailFor:withError fails with While Using the App location permission in iOS 10 & 11

### ISSUE THREAD

**Issue by sacred0x01** [kontaktio/kontakt-ios-sdk#52]
On ios10-11 if app receive `While Using the App` location permission, KTKBeaconManager delegate fails in 
```
func beaconManager(_ manager: KTKBeaconManager,  monitoringDidFailFor region: KTKBeaconRegion?, withError error: Error?) {
}
```
with `kCLErrorDomain error 4`

In case of `Always Allow` app works correct. 
In both cases we only change location permission.
All keys for requesting permission already added into info.plist.

**Comment by stoprocent** [comment]
Hi @sacred0x01

I think you have answered your own question :) 

Error Code `4` is [regionMonitoringDenied](https://developer.apple.com/documentation/corelocation/clerror.code/1423754-regionmonitoringdenied)

> A constant indicating that access to the region monitoring service was denied by the user.

If you look here [kCLAuthorizationStatusAuthorizedWhenInUse](https://developer.apple.com/documentation/corelocation/clauthorizationstatus/kclauthorizationstatusauthorizedwheninuse)

> This authorization does not allow you to use APIs that could launch your app in response to an event, such as region monitoring and the significant location change services.

**Comment by sacred0x01** [comment]
So what should we do in case of this permission? No way to use it with our beacon feature?

**Comment by stoprocent** [comment]
You can range beacons in the foreground and determine beacons states and use `KTKDevicesManager` together with [The bluetooth-central Background Execution Mode
](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW6)

**Comment by sacred0x01** [comment]
Fix me if i am not correct, but
`You can range beacons in the foreground `

**Comment by sacred0x01** [comment]
Oh, finally got the idea: use startRangingBeacons. Thanks)
