### ISSUE TITLE
Parameters and available operations

### ISSUE THREAD

**Issue by TudorZg** [kontaktio/kontakt-ios-sdk#54]
Hello,

I would like to find out what the default value for Android's 'activityCheckConfiguration' iOS counterpart is and if there is a way to configure it. Also, is there an iOS version of the 'onIBeaconLost' event? 

I could also not find the default values for monitoring: scanning period, the interval period, the timeout etc.

Thank you!

**Comment by stoprocent** [comment]
Hi Please refer to this page: https://developer.kontakt.io/mobile/ios/detecting/
