### ISSUE TITLE
KTKEddystoneManager.centralState is always 0

### ISSUE THREAD

**Issue by pvaltorta** [kontaktio/kontakt-ios-sdk#57]
When I check value of KTKEddystoneManager.centralState to verify if Bluetooth is on or off, value of property is always 0 (zero).
Do I need to call some other function to start Bluetooth state check?

**Comment by homoky** [comment]
@pvaltorta Hello, we are facing same issue as you here and in #56 as well. Can you please tell us how did you solve this? Thank you for feedback.

**Comment by stoprocent** [comment]
Duplicate of #56

**Comment by nashfive** [comment]
Got the same issue. Not a duplicate of #56
I have created #73
