### ISSUE TITLE
KTKBluetoothManagerDelegate

### ISSUE THREAD

**Issue by sotrosh** [kontaktio/kontakt-ios-sdk#6]
Hello,

In the documentation and readme.md there is a mention about KTKBluetoothManagerDelegate protocol: http://developer.kontakt.io/ios-sdk/quickstart/
But there is no in kontak.io SDK.
Did you mean KTKEddystoneManagerDelegate?

**Comment by stoprocent** [comment]
Thanks for the tip :+1:  It is `KTKEddystoneManagerDelegate` will update docs later on today :) Good catch.
