### ISSUE TITLE
CLBeacon proximity always returning .near value

### ISSUE THREAD

**Issue by GelatosLazaro** [kontaktio/kontakt-ios-sdk#61]
Ranging beacon is always returning .near proximity.

` func beaconManager(_ manager: KTKBeaconManager, didRangeBeacons beacons: [CLBeacon], in region: KTKBeaconRegion) {
        for beacon in beacons {
          
            print(beacon)
            print("proximity: \( beacon.proximity.rawValue) accuracy:\(beacon.accuracy)")
            
            switch beacon.proximity
            {
            case CLProximity.far:
                print("far")
                break
                
            case CLProximity.immediate:
                 print("immediate")
                break
                
            case CLProximity.near:
                 print("near")
                break
            case .unknown:
                print("near")
                break
               
            }
            
        }
    }`

Is this a Kontakt.io issue?

**Comment by stoprocent** [comment]
We are using CLLocationManager underneath for iBeacon protocol. You should try using simple `CLLocationManager` ranging and have a look if it's the same. If you will get different results please reopen this issue

**Comment by vidhyasri2106** [comment]
@stoprocent i am using CLLocation manager only. But i am also facing same issue. WHat might be the cause?
@GelatosLazaro Did you figure out the issue?
