### ISSUE TITLE
Beacon Pro

### ISSUE THREAD

**Issue by antonino-tocco** [kontaktio/kontakt-ios-sdk#62]
Hi, I need to ranging or monitoring beacon pro with a behaviour like the proximity manager of the android sdk.
There is a sample or a tutorial to do this?

**Comment by stoprocent** [comment]
Hi @antonino-tocco 

Please have a look here: https://developer.kontakt.io/mobile/ios/detecting/
If you need more code examples have a look here: https://github.com/kontaktio/kontakt-ios-sdk/tree/master/Examples/iOS/
