### ISSUE TITLE
didEnter not fired

### ISSUE THREAD

**Issue by Lawris** [kontaktio/kontakt-ios-sdk#68]
I am not able to get the `didEnter` and the `didExitRegion` events fired.
I downloaded the iOS sample this git provides. I did put my API key and set my Kontakt iBeacon KontaktProximityUUID in the Constants.swift file. Some things are strange : 

- In the ranging beacons section it says it is able to range 2/3 beacons however, I only have one beacon near me
- In the monitoring region section (the more important for me), when I click the start button it tells me the monitoring started with my proximity UUID and major/minor values set to null ; however the events are not fired. (Although I've been following the advices right [here](https://support.kontakt.io/hc/en-gb/articles/207297430-didEnterRegion-method-not-being-called-)). 
- In the nearby scanning section, it is able to detect and identify my beacon perfectly.

I'm probably missing something somewhere, maybe its the major/minor values that needs to be set so the Kontakt SDK is able to monitor my beacon ? 

Any help would be greatly appreciated !

**Comment by Lawris** [comment]
Thank you for your answer. 

I've already added those keys in the Info.plist, in fact I had the notification when I first installed the app on my phone to give full location access. Nothing else ?

**Comment by stoprocent** [comment]
How do you simulate enter exit events ? Are you going away form the device or pulling out the battery ?

**Comment by Lawris** [comment]
I've set the transmission power to 0 to be sure. I simulate like this : 

- Start the monitoring function

- Go for about 10/20 meters away for like 1 minute 

- Come back 

But nothing on the logs.

**Comment by stoprocent** [comment]
It's possible 10-20 meters will not be enough. Try changing TX power to some low value like 1(-20dbm) and try again for a bit longer. Enters and Exits notifications are managed and triggered by iOS CoreLocation so I cannot guarantee what time is required for the event to happen.

**Comment by Lawris** [comment]
Ok so yeah CoreLocation is not super reactive but it works.
Thanks for your help !
