### ISSUE TITLE
Error when uploading app with new iOS sdk

### ISSUE THREAD

**Issue by vanessa05** [kontaktio/kontakt-ios-sdk#7]
I installed the new kontakt iOS sdk (Version: 1.0.4) as it's explained in the quick start guide.

I wrote code to detect my eddystone. In foreground and in background, it's ok :-)
I created an archive of my target => ok. 

But when I try to upload this archive to the App Store, I see errors messages like on the screenshot.
![capture d ecran 2016-02-10 a 10 22 25](https://cloud.githubusercontent.com/assets/6204577/12943254/599ce37a-cfe0-11e5-834a-7ed8aa1de6d4.png)

Can you please tell me what I'm doing wrong ? 

Thanks for your help

**Comment by stoprocent** [comment]
Hi @vanessa05 

I think I solved all the issues with architectures and bitcode now. I want to make sure next update is bug free and I will release it tomorrow. 

It is related to this bug http://www.openradar.me/radar?id=6409498411401216

What you can do now to make it working is to add build phase script in your project and paste this:
```
bash ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/KontaktSDK.framework/strip-frameworks.sh
```

**Comment by vanessa05** [comment]
Hi @stoprocent 

Indeed, I just added build phase script as you wrote and now it's ok ! I can upload my build to the App Store without problem ! :-)

Thank you very much for your help !

**Comment by stoprocent** [comment]
No worries :) Glad it helped
