### ISSUE TITLE
Monitored regions nil

### ISSUE THREAD

**Issue by MrNickBarker** [kontaktio/kontakt-ios-sdk#8]
While ranging beacons work, region monitoring doesn't.

The code is unchanged from the Quickstart guide:
```
NSUUID *proximityUUID = [[NSUUID alloc] initWithUUIDString:uuid];
    
// Create region instance
KTKBeaconRegion *region = [[KTKBeaconRegion alloc] initWithProximityUUID:proximityUUID identifier:identifier];
    
// Start Monitoring
[self.beaconManager startMonitoringForRegion:region];
```

This delegate method is called with a *nil* region.
```
- (void)beaconManager:(KTKBeaconManager *)manager didStartMonitoringForRegion:(__kindof KTKBeaconRegion *)region
```

If I later log `[self.beaconManager monitoredRegions]` I also get nil.

I'm using KontaktSDK 1.0.5, and an iPhone 6s iOS 9.1.  I'm testing with three beacons (iBeacon profile).

**Comment by stoprocent** [comment]
Hi @MrNickBarker 

Did you call [requestLocationAlwaysAuthorization](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Classes/KTKBeaconManager.html#//api/name/requestLocationAlwaysAuthorization)?

Did you try method [beaconManager:monitoringDidFailForRegion:withError:](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Protocols/KTKBeaconManagerDelegate.html#//api/name/beaconManager:monitoringDidFailForRegion:withError:) ?

Can you check if there is any error?

Also what I would suggest is to call [stopMonitoringForAllRegions](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Classes/KTKBeaconManager.html#//api/name/stopMonitoringForAllRegions) before start monitoring. Just in case as monitored regions are stored by iOS until you stop monitoring them. It will be enough to call stop method once and then remove it.

**Comment by MrNickBarker** [comment]
Hi @stoprocent thanks for the quick response.

I called all of the methods you suggested but still no luck. 

Here is my test code:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [Kontakt setAPIKey:@"my-api-key"];
    
    // Initiate Beacon Manager
    self.beaconManager = [[KTKBeaconManager alloc] initWithDelegate:self];
    
    // Request Location Authorization
    [self.beaconManager requestLocationAlwaysAuthorization];
    
    // Kontakt.io proximity UUID
    NSUUID *proximityUUID = [[NSUUID alloc] initWithUUIDString:@"f7826da6-4fa2-4e98-8024-bc5b71e0893e"];
    
    // Create region instance
    KTKBeaconRegion *region = [[KTKBeaconRegion alloc] initWithProximityUUID:proximityUUID identifier:@"identifier"];
    
    [self.beaconManager stopMonitoringForAllRegions];
    
    // Start Monitoring
    [self.beaconManager startMonitoringForRegion: region];
    
    return YES;
}

- (void)beaconManager:(KTKBeaconManager*)manager didChangeLocationAuthorizationStatus:(CLAuthorizationStatus)status;
{
    NSLog(@"Change authorization %zd", status);
}

- (void)beaconManager:(KTKBeaconManager*)manager didEnterRegion:(__kindof KTKBeaconRegion*)region
{
    NSLog(@"Enter region %@", region);
}

- (void)beaconManager:(KTKBeaconManager*)manager didExitRegion:(__kindof KTKBeaconRegion*)region
{
    NSLog(@"Exit region %@", region);
}

- (void)beaconManager:(KTKBeaconManager*)manager didRangeBeacons:(NSArray <CLBeacon *>*)beacons inRegion:(__kindof KTKBeaconRegion*)region
{
    NSLog(@"Ranged beacons count: %lu", [beacons count]);
}

- (void)beaconManager:(KTKBeaconManager *)manager didDetermineState:(CLRegionState)state forRegion:(__kindof KTKBeaconRegion *)region
{
    NSLog(@"Determine state for region %@", region.identifier);
}

- (void)beaconManager:(KTKBeaconManager *)manager rangingBeaconsDidFailForRegion:(__kindof KTKBeaconRegion *)region withError:(NSError *)error
{
    NSLog(@"Ranging failed: %@", error.localizedDescription);
}

- (void)beaconManager:(KTKBeaconManager *)manager monitoringDidFailForRegion:(__kindof KTKBeaconRegion *)region withError:(NSError *)error
{
    NSLog(@"Monitoring failed for region: %@ - %@", region.identifier, error.localizedDescription);
}
```

These are my logs:
```
2016-02-15 12:06:53.207 iBeacon Prototype[6836:3697034] Change authorization 3
2016-02-15 12:06:53.233 iBeacon Prototype[6836:3697034] Change authorization 3
```

With the same code if I start ranging instead of monitoring regions I can see the beacons no problem.

**Comment by MrNickBarker** [comment]
If it helps the bacon firmware is at 3.1. I don't know if updating to 4.0 would change anything.

**Comment by stoprocent** [comment]
@MrNickBarker Enter will not be called if you are already in range of the beacons. This is how CoreLocation works.

What I would suggest is start monitoring when all the beacons are not in range and then bring one back and see if you are getting a call.

Im just taking of the batteries out while testing. You can try same thing

**Comment by MrNickBarker** [comment]
@stoprocent Thanks for the suggestion but still no change.

* I removed batteries from all three beacons and then put one back in. 
* I tried moving the beacon outside then starting monitoring and bringing the beacon back in.
* I tried moving the phone out of range, starting monitoring and then coming back.
* I logged again ```[self.beaconManager monitoredRegions]``` at various points but it always returns nil.

**Comment by stoprocent** [comment]
@MrNickBarker yup there is something with proprerty `monitoredRegions` :+1: 
Can you just try one thing for me?
Insted of `monitoredRegions` on `KTKBeaconManager` can you try this:

``` Objective-C
NSLog(@"Regions: %@", [CLLocationManager new].monitoredRegions);
```

**Comment by MrNickBarker** [comment]
@stoprocent This is what I get:
```Regions: {(
    CLBeaconRegion (identifier:'identifier.Proximity.F7826DA6-4FA2-4E98-8024-BC5B71E0893E', uuid:<__NSConcreteUUID 0x157e35f70> F7826DA6-4FA2-4E98-8024-BC5B71E0893E, major:(null), minor:(null))
)}```

**Comment by stoprocent** [comment]
@MrNickBarker ... Good so region is monitored. There is an issue with our beacon manager class property. I'm on it now.

This is not related to your problem tho. Can you try changing one of the beacon's proximity UUID to something else and try to monitor that?

**Comment by MrNickBarker** [comment]
@stoprocent I have done it now (also a few times while testing) but still the same issue. I have tried again all the previous steps with pulling out the battery, moving the phone etc.

**Comment by stoprocent** [comment]
@MrNickBarker OK :+1: 
What I'm going to do now is to go trough the bug you found and do some more testing. I will let you know when Im done. 

Thanks for the input!

**Comment by stoprocent** [comment]
Hi @MrNickBarker 
There was an issue with regions monitoring when **NOT** using `security` and `4.0 firmware` :+1: so thank you very much for spotting this. It's great to see community input in new SDK.

Can you please try version `1.0.6` and report if it fixed your issues? Also before you try please remove app from the device first to make sure caches are clean :)

Thanks again

M

**Comment by MrNickBarker** [comment]
@stoprocent Actually the beacons I'm using are still on 3.1 but 1.0.6 seems to have fixed the issue. I'm getting exit/enter region delegate calls now. Thank you very much for your help :+1:

**Comment by stoprocent** [comment]
Great news! What I was saying is that issue was happening only when using 3.1 and below.
If you need more help just let me know.
