### ISSUE TITLE
Request state for region

### ISSUE THREAD

**Issue by greencoppercompany** [kontaktio/kontakt-ios-sdk#9]
Hi!

We have problem getting both state for a given regions and list of regions monitored (i saw there is already a bug opened for the last point).

Regarding requestStateForRegion: we never get any callback for any beacons. Is this something that is working on our test suite?

Best,
Loïc

**Comment by stoprocent** [comment]
Hi @greencoppercompany 

As in Core Location documentation [requestStateForRegion:](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instm/CLLocationManager/requestStateForRegion:) :

> The region whose state you want to know. This object must be an instance of one of the standard region subclasses provided by Map Kit. You cannot use this method to determine the state of custom  regions you define yourself. 

So you cant just pass any region and wait for the state to be reported.

As far as I understand this has to be a region provided by system from a delegate call like didRange etc.

`locationManager:didDetermineState:forRegion:` is also called when region you are monitoring has a flag [notifyEntryStateOnDisplay](https://kontaktio.github.io/kontakt-ios-sdk/Documentation/html/Classes/KTKBeaconRegion.html#//api/name/notifyEntryStateOnDisplay) set to `YES` / `true` and user lights up the iPhone screen.

In Apple documentation:

> When set to true, the location manager sends beacon notifications when the user turns on the display and the device is already inside the region. These notifications are sent even if your app is not running. In that situation, the system launches your app into the background so that it can handle the notifications. In both situations, the location manager calls the locationManager:didDetermineState:forRegion: method of its delegate object. 

Empty list of monitored regions is in fact related to #8 and this is something I will fix and publish soon as a new release. I will keep you guys updated ASAP.

**Comment by stoprocent** [comment]
#8

**Comment by greencoppercompany** [comment]
Thanks for feedback. In fact, there is a requestStateForRegion: function in your SDK that take a KTKBeaconRegion. What i'm doing is:

- create KTKBeaconRegion A
- startMonitoring:A
- follow by a call to requestStateForRegion:A to detect case where users are already in the region and fire internally a fake didEnter

and I get not callback at all.

**Comment by stoprocent** [comment]
I know but `requestStateForRegion:` is just a forward to `CLLocationManager` delegate so it behaves exactly as `Core Location`. I will have to probably remove it as it causing confusions :( ...

For your case its better to start monitoring and also do ranging in monitored region to detect if users are already in range. So just instead of requesting state start raning for few seconds.

**Comment by stoprocent** [comment]
@greencoppercompany regarding issue #8 please try updating SDK to version `1.0.6`. It was released few minutes ago.

Let me know please and remove your app from the phone first to make sure caches are clean.

**Comment by greencoppercompany** [comment]
Hummm but requestStateForRegion: is supposed to give a status. I don't get why we get no callback, even if the call is a forward to Apple code. Can it be linked to the property notifyEntryStateOnDisplay not properly setup?

What value do you put in your SDK?

**Comment by stoprocent** [comment]
@greencoppercompany `notifyEntryStateOnDisplay` by default is set to `NO` both in `CoreLocation` and in `KontaktSDK`. `requestStateForRegion:` is **not** is supposed to give a status of a region object you have created.

**Comment by stoprocent** [comment]
Hi @greencoppercompany, you were right and I was wrong :+1: 
I did some more testing requesting a state and in fact it should report and it does.
I was more focused on just monitoring and ranging. I did some regions fixes in version `1.0.6` released yesterday.

Have a look:
![Screen](http://f.cl.ly/items/0n0O2v0f1U2O163Z2o1D/Screenshot%202016-02-16%2017.26.15.png)

**Comment by greencoppercompany** [comment]
Cool! I did some tests and we now have the correct behaviour.
The idea behind that is to help us trigger action even if users are already inside a region when the app starts.

Thanks for your help!

**Comment by stoprocent** [comment]
@greencoppercompany no worries, thanks for spotting this. Can I close the issue?

**Comment by greencoppercompany** [comment]
Sure!
